openapi: 3.0.0
info:
  title: Delilah restó API
  description: This is an API project for Acamica Fullstack - 2021.
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: users
    description: Everything about the Users
  - name: products
    description: Everything about the Products
  - name: orders
    description: Everything about the Orders

paths:
  ############ USERS ##############
  /users/all:
    get:
      tags:
        - users
      summary: Returns a list of users.
      description: Get all users from Delilah Restó
      operationId: all
      security: 
        - tokenAuth: []
      responses:
        '200':   
          description: A JSON array of users
          content:
            application/json:
              example:
                - id: 1
                  user: admin
                  name: Admin name
                  surname: Admin surname
                  email: admin@example.com
                  phone: 123 456 789
                  address: Address user
                  role: admin
                - id: 2
                  user: user
                  name: User name
                  surname: User surname
                  email: user@example.com
                  phone: 123 456 789
                  address: Address user
                  role: user
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                error: string 
  /users/getbyid:
    get:
      tags:
        - users
      summary: Returns a user by ID
      description: Get a user from Delilah Restó
      operationId: getbyid
      responses:
        '200':   
          description: A JSON of user
          content:
            application/json:
              example:
                  id: 1
                  user: admin
                  name: Admin name
                  surname: Admin surname
                  email: admin@example.com
                  phone: 123 456 789
                  address: Address user
                  role: admin
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                error: string 
components:
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: x-auth-token
      description: JWT
